name = "RABBIT"
uuid = "98960a00-302f-469e-9595-275b70d10766"
authors = ["Adriana Ghiozzi <ghiozzia@fusion.gat.com>"]
version = "2.0.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
